# Generated by Django 5.0 on 2026-03-27 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Clear title helps Sol Plaatje staff understand quickly', max_length=200)),
                ('issue_type', models.CharField(choices=[('water', 'Water Leak'), ('electricity', 'Electricity Issue'), ('pothole', 'Pothole'), ('waste', 'Waste Management')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(help_text='e.g., Bultfontein Rd & 5th Ave, Galeshewe, Kimberly', max_length=200)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('reporter_name', models.CharField(max_length=100)),
                ('reporter_email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='issues/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
