# Generated by Django 6.0.3 on 2026-03-27 21:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('working_hours', models.CharField(default='Mon-Fri 08:00-16:30', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='📍', max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('department', models.CharField(help_text='Responsible department', max_length=100)),
                ('estimated_response_time', models.IntegerField(default=48, help_text='Hours to respond')),
                ('auto_assign_to', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Issue Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IssueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='issues/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IssueVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_ip', models.GenericIPAddressField()),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App')], max_length=20)),
                ('recipient', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at'], 'verbose_name': 'Issue', 'verbose_name_plural': 'Issues'},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='image',
        ),
        migrations.AddField(
            model_name='issue',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='ai_category_suggestion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_staff',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issue',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='reporting.issue'),
        ),
        migrations.AddField(
            model_name='issue',
            name='estimated_resolution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='external_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='in_progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_accessible',
            field=models.BooleanField(default=True, help_text='ADA compliance'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='location_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='location_description',
            field=models.TextField(blank=True, help_text='Additional location details'),
        ),
        migrations.AddField(
            model_name='issue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='issue',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('awaiting_parts', 'Awaiting Parts'), ('scheduled', 'Scheduled'), ('resolved', 'Resolved'), ('verified', 'Verified by Reporter'), ('closed', 'Closed'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='reporter_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='reports_count',
            field=models.IntegerField(default=0, help_text='Times reported by community'),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='sla_breach_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='sla_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='issue',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='issue',
            name='suburb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='suggested_priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('critical', 'Critical')], help_text='AI-suggested priority', max_length=10),
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='issue',
            name='tracking_code',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issue',
            name='verification_status',
            field=models.CharField(choices=[('none', 'Not Verified'), ('pending', 'Pending Verification'), ('verified', 'Community Verified'), ('disputed', 'Disputed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='ward',
            field=models.CharField(blank=True, help_text='Municipal ward', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('water', 'Water Leak'), ('electricity', 'Electricity Issue'), ('pothole', 'Pothole'), ('waste', 'Waste Management'), ('streetlight', 'Street Light'), ('drainage', 'Drainage Issue'), ('noise', 'Noise Complaint'), ('safety', 'Public Safety'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='location',
            field=models.CharField(help_text='Street address or landmark', max_length=200),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('awaiting_parts', 'Awaiting Parts'), ('scheduled', 'Scheduled'), ('resolved', 'Resolved'), ('verified', 'Verified by Reporter'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(help_text='Clear, descriptive title', max_length=200),
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='reporting.department'),
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.issuecategory'),
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('is_official', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reporting.issue')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='issue_images', to='reporting.issueimage'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status', '-created_at'], name='reporting_i_status_219cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['priority', '-created_at'], name='reporting_i_priorit_106abc_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['tracking_code'], name='reporting_i_trackin_845604_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['assigned_department', 'status'], name='reporting_i_assigne_bdfb66_idx'),
        ),
        migrations.AddField(
            model_name='issuevote',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reporting.issue'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reporting.issue'),
        ),
        migrations.AlterUniqueTogether(
            name='issuevote',
            unique_together={('issue', 'voter_ip')},
        ),
    ]
