# Generated by Django 6.0.3 on 2026-03-27 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_department_issuecategory_issueimage_issuevote_and_more'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_condition', models.CharField(choices=[('time_in_status', 'Time in Status'), ('sla_breach', 'SLA Breach'), ('priority_change', 'Priority Change'), ('no_response', 'No Response')], max_length=50)),
                ('trigger_value', models.IntegerField(help_text='Hours or count depending on condition')),
                ('escalate_to_role', models.CharField(max_length=50)),
                ('escalate_to_department', models.CharField(max_length=100)),
                ('notify_original_owner', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('notify_on_status_change', models.BooleanField(default=True)),
                ('notify_on_progress', models.BooleanField(default=True)),
                ('notify_on_resolution', models.BooleanField(default=True)),
                ('notify_on_sla_breach', models.BooleanField(default=True)),
                ('notify_on_community_activity', models.BooleanField(default=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=False)),
                ('digest_frequency', models.CharField(choices=[('instant', 'Instant'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='instant', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('technician', 'Technician'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('admin', 'Administrator')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('max_concurrent_issues', models.IntegerField(default=10)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('current_load', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='statusupdate',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Status Update', 'verbose_name_plural': 'Status Updates'},
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='automation_rule',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='estimated_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='location_visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='photos_attached',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('awaiting_parts', 'Awaiting Parts'), ('scheduled', 'Scheduled'), ('resolved', 'Resolved'), ('verified', 'Verified by Reporter'), ('closed', 'Closed'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='public_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='update_type',
            field=models.CharField(choices=[('manual', 'Manual Update'), ('automatic', 'System Update'), ('escalation', 'Escalation'), ('sla', 'SLA Reminder')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='statusupdate',
            name='new_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('awaiting_parts', 'Awaiting Parts'), ('scheduled', 'Scheduled'), ('resolved', 'Resolved'), ('verified', 'Verified by Reporter'), ('closed', 'Closed'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statusupdate',
            name='updated_by',
            field=models.CharField(help_text='Staff member name', max_length=100),
        ),
        migrations.CreateModel(
            name='AutomatedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('auto_assign', 'Auto Assignment'), ('auto_priority', 'Priority Update'), ('auto_category', 'Category Suggestion'), ('sla_reminder', 'SLA Reminder'), ('auto_close', 'Auto Closure'), ('duplicate_check', 'Duplicate Check')], max_length=50)),
                ('action_taken', models.CharField(max_length=200)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('accepted_by', models.CharField(blank=True, max_length=100)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_actions', to='reporting.issue')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='EscalationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalated_at', models.DateTimeField(auto_now_add=True)),
                ('from_role', models.CharField(blank=True, max_length=50)),
                ('to_role', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='reporting.issue')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.escalationrule')),
            ],
            options={
                'ordering': ['-escalated_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_first_contact', models.IntegerField(blank=True, null=True)),
                ('time_to_dispatch', models.IntegerField(blank=True, null=True)),
                ('time_on_hold', models.IntegerField(default=0)),
                ('actual_resolution_time', models.IntegerField(blank=True, null=True)),
                ('reporter_satisfaction', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('community_engagement', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('staff_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('materials_used', models.JSONField(blank=True, default=list)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='reporting.issue')),
            ],
            options={
                'verbose_name_plural': 'Issue Metrics',
            },
        ),
        migrations.CreateModel(
            name='SLATracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_first_response', models.IntegerField(default=4)),
                ('target_resolution', models.IntegerField(default=48)),
                ('target_acknowledgement', models.IntegerField(default=2)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('first_response_breached', models.BooleanField(default=False)),
                ('resolution_breached', models.BooleanField(default=False)),
                ('acknowledgement_breached', models.BooleanField(default=False)),
                ('reminder_1_sent', models.BooleanField(default=False)),
                ('reminder_2_sent', models.BooleanField(default=False)),
                ('warning_sent', models.BooleanField(default=False)),
                ('breach_notice_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla', to='reporting.issue')),
            ],
            options={
                'verbose_name': 'SLA Tracking',
                'verbose_name_plural': 'SLA Trackings',
            },
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='tracking.staffmember'),
        ),
        migrations.CreateModel(
            name='IssueAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reporting.issue')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tracking.staffmember')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('issue', 'staff')},
            },
        ),
    ]
